### PR TITLE
Automatically populate a file with markdown routes...

### PR DESCRIPTION
**Pull request by juancuiule**
Run generator.js and look for a file called routes.md, the part that is missing is to append this to de home.md or home.html

### CODE REVIEW

**Comment by huytd** [comment]
Great! Can you provide the sample content of the `routes.md`?

**Comment by juancuiule** [comment]
routes

**Comment by juancuiule** [comment]
I think that it will be possible to parse this into html and add in a footer of every post
Another workaround would be to make some kind of navigator aside with this data...

**Comment by huytd** [comment]
👍 Thank you so much!

**Pull request merged**
